/*
 * Readings of the French voice (owner's decision of 10/10/2026), keyed by the word in
 * capitals without accents. Drafted from the 229 words in capitals seen at least 20
 * times in the articles, then confirmed by the owner by listening to them all
 * (docs/runbooks/voix.md). Raise `version` at every change: the French recordings
 * are then made again.
 *   say: the words read instead; spell: letter by letter; phonemes: said exactly.
 * `names` apply however the name is written (SALL, Sall); `capitals` only to words
 * written in capitals.
 */

export type Reading = { say: string } | { spell: true } | { phonemes: string };

export interface FrenchLexicon {
  version: number;
  capitals: Readonly<Record<string, Reading>>;
  names: Readonly<Record<string, Reading>>;
}

export const FRENCH_LEXICON: FrenchLexicon = {
  version: 1,
  names: {
    SALL: { say: "Sal" },
    FALL: { say: "Fal" },
    TALL: { say: "Tal" },
    THIAM: { say: "Tyam" },
    WADE: { say: "Ouade" },
    SOW: { say: "So" },
    MBOW: { say: "Mbo" },
    LY: { say: "Li" },
    DIEYE: { say: "Dieye" },
    GUEYE: { say: "Gueye" },
    MBACKE: { say: "Mbaké" },
    NDOYE: { phonemes: "ndˈɔj" },
    DIAGNE: { phonemes: "djˈaɲ" },
    NIANG: { phonemes: "njˈaŋ" },
    DIENG: { phonemes: "djˈɛŋ" },
    MBENGUE: { phonemes: "mbˈɛŋɡ" },
  },
  capitals: {
    DE: { say: "de" },
    DES: { say: "des" },
    FCFA: { say: "francs CFA" },
    AU: { say: "au" },
    DU: { say: "du" },
    FAYE: { say: "Faye" },
    TITRE: { say: "titre" },
    DIOP: { say: "Diop" },
    LA: { say: "la" },
    NDIAYE: { say: "Ndiaye" },
    ET: { say: "et" },
    SONKO: { say: "Sonko" },
    BA: { say: "Ba" },
    SARR: { say: "Sarr" },
    CEDEAO: { say: "Cédéao" },
    JOJ: { spell: true },
    DIOUF: { say: "Diouf" },
    MINISTRES: { say: "Ministres" },
    LE: { say: "le" },
    SA: { say: "sa" },
    CFA: { spell: true },
    MAERSA: { say: "Maersa" },
    FPT: { spell: true },
    SY: { say: "Sy" },
    PME: { spell: true },
    SARRE: { say: "Sarré" },
    UEMOA: { say: "Uémoa" },
    GIZ: { spell: true },
    MFPAI: { spell: true },
    MESURES: { say: "mesures" },
    CFP: { spell: true },
    COMMUNICATIONS: { say: "communications" },
    IA: { spell: true },
    COVID: { say: "Covid" },
    PSE: { spell: true },
    CONSEIL: { say: "Conseil" },
    MCTN: { spell: true },
    DER: { spell: true },
    SENE: { say: "Sène" },
    EN: { say: "en" },
    DIALLO: { say: "Diallo" },
    COMMUNICATION: { say: "communication" },
    TEXTES: { say: "textes" },
    OMS: { spell: true },
    INDIVIDUELLES: { say: "individuelles" },
    NDAO: { say: "Ndao" },
    LEGISLATIFS: { spell: true },
    PROJET: { say: "projet" },
    CISSE: { say: "Cissé" },
    MBAYE: { say: "Mbaye" },
    SEM: { spell: true },
    ECOFEST: { say: "Ecofest" },
    MINISTRE: { say: "Ministre" },
    REGLEMENTAIRES: { say: "réglementaires" },
    COMMUNIQUE: { say: "communiqué" },
    FMI: { spell: true },
    DIA: { say: "Dia" },
    LO: { say: "Lo" },
    MASAE: { say: "Masae" },
    II: { say: "deux" },
    SENELEC: { say: "Senelec" },
    MERCREDI: { say: "mercredi" },
    BAD: { spell: true },
    DIAO: { say: "Diao" },
    OLAC: { say: "Olac" },
    ONU: { spell: true },
    ONAS: { say: "Onas" },
    POUR: { say: "pour" },
    GTA: { spell: true },
    PETROSEN: { spell: true },
    APIX: { say: "Apix" },
    LES: { say: "les" },
    NGOM: { say: "Ngom" },
    ESS: { spell: true },
    OMVG: { spell: true },
    AIBD: { say: "Aibd" },
    KANE: { say: "Kane" },
    AI: { spell: true },
    CICAD: { say: "Cicad" },
    AFD: { spell: true },
    FJ: { spell: true },
    TER: { spell: true },
    SECK: { say: "Seck" },
    MFPT: { spell: true },
    OMVS: { spell: true },
    COJOJ: { say: "Cojoj" },
    ONG: { spell: true },
    FORMATION: { say: "formation" },
    MSHP: { spell: true },
    SONES: { say: "Sones" },
    ISRA: { say: "Isra" },
    VISITE: { say: "visite" },
    NGOUILLE: { say: "Ngouille" },
    MFA: { spell: true },
    ALY: { say: "Aly" },
    BTS: { spell: true },
    SONACOS: { say: "Sonacos" },
    PPP: { spell: true },
    AMCOW: { say: "Amcow" },
    JICA: { say: "Jica" },
    UN: { say: "un" },
    FORCES: { say: "Forces" },
    ONFP: { spell: true },
    SENEGAL: { say: "Sénégal" },
    PRESIDENT: { say: "Président" },
    EAU: { say: "eau" },
    GIE: { spell: true },
    SENRM: { spell: true },
    DIEME: { say: "Dieme" },
    CAMARA: { say: "Camara" },
    MW: { spell: true },
    PREMIER: { say: "Premier" },
    CAN: { spell: true },
    PRES: { say: "près" },
    PROMOREN: { spell: true },
    UNICEF: { say: "Unicef" },
    ATELIER: { say: "atelier" },
    REPUBLIQUE: { say: "République" },
    OFOR: { say: "Ofor" },
    SAR: { spell: true },
    SEN: { spell: true },
    DG: { spell: true },
    UIT: { spell: true },
    ARMEES: { say: "armées" },
    MTN: { spell: true },
    PMI: { spell: true },
    BRT: { spell: true },
    CFPT: { spell: true },
    PUDC: { spell: true },
    FIDA: { say: "Fida" },
    MHA: { spell: true },
    MEFPT: { spell: true },
    GAYE: { say: "Gaye" },
    ODD: { spell: true },
    BALDE: { say: "Baldé" },
    PIB: { spell: true },
    SUR: { say: "sur" },
    CISS: { spell: true },
    APDA: { say: "Apda" },
    UNESCO: { say: "Unesco" },
    SG: { spell: true },
    DIATTA: { say: "Diatta" },
    CDC: { spell: true },
    BTP: { spell: true },
    VI: { say: "six" },
    AEME: { say: "Aeme" },
    ANER: { say: "Aner" },
    TOURE: { say: "Touré" },
    FONGIP: { spell: true },
    ISEP: { say: "Isep" },
    MEA: { spell: true },
    ASER: { say: "Aser" },
    ARTP: { spell: true },
    KABA: { say: "Kaba" },
    UNE: { say: "une" },
    DFPT: { spell: true },
    RGS: { spell: true },
    UA: { spell: true },
    ENTRE: { say: "entre" },
    MEPM: { spell: true },
    BCEAO: { spell: true },
    NDOUR: { say: "Ndour" },
    DAGE: { say: "Dage" },
    NATIONALE: { say: "nationale" },
    MINISTERE: { say: "Ministère" },
    PROFESSIONNELLE: { say: "professionnelle" },
    PUMA: { say: "Puma" },
    DPG: { spell: true },
    ITIE: { say: "Itie" },
    FIT: { spell: true },
    CEMGA: { say: "Cemga" },
    SANE: { say: "Sané" },
    FONSIS: { spell: true },
    ANACIM: { say: "Anacim" },
    FAO: { spell: true },
    TECHNIQUE: { say: "technique" },
    EIES: { say: "Eies" },
    ASPT: { spell: true },
    AGEROUTE: { say: "Ageroute" },
    SOMISEN: { say: "Somisen" },
    UE: { spell: true },
    BNDE: { spell: true },
    "PASEA-RD": { say: "Pasea-rd" },
    MAER: { say: "Maer" },
    PASEA: { say: "Pasea" },
    SAPCO: { say: "Sapco" },
    KA: { say: "Ka" },
    BOAD: { say: "Boad" },
    DIRECT: { say: "direct" },
    "CFPT-SJ": { spell: true },
    CFMPL: { spell: true },
    DANS: { say: "dans" },
    ENFEFS: { spell: true },
    VAE: { spell: true },
    SATOLIC: { say: "Satolic" },
    SONAGED: { say: "Sonaguède" },
    CPI: { spell: true },
    SENGHOR: { say: "Senghor" },
    PDG: { spell: true },
    ARCOP: { say: "Arcop" },
    MSGBC: { spell: true },
    INPG: { spell: true },
    PCA: { spell: true },
    SON: { say: "son" },
    DPGI: { spell: true },
    PISEA: { say: "Pisea" },
    FSRP: { spell: true },
    CGES: { spell: true },
    PDCEJ: { spell: true },
    MSAS: { spell: true },
  },
};
