import data from "./open-source.json";

/** A package shipped in the app, with what its licence asks to credit (LIC-01). */
export interface OpenSourcePackage {
  name: string;
  version: string;
  licence: string;
  copyright: string[];
  url: string | null;
  /** Index of its licence text in `texts`. */
  text: number;
}

export interface OpenSourceNotices {
  packages: OpenSourcePackage[];
  /** Each distinct licence text once. */
  texts: string[];
}

/** Generated by `pnpm notices` from the app's production bundle: never edited by hand. */
export const OPEN_SOURCE: OpenSourceNotices = data;
