import type { fontFace } from "@bgs/ui";
import { useFonts } from "expo-font";
import NotoSans_400Regular from "../../assets/fonts/NotoSans_400Regular.ttf";
import NotoSans_600SemiBold from "../../assets/fonts/NotoSans_600SemiBold.ttf";
import NotoSans_700Bold from "../../assets/fonts/NotoSans_700Bold.ttf";
import NotoSans_800ExtraBold from "../../assets/fonts/NotoSans_800ExtraBold.ttf";
import NotoSerif_600SemiBold from "../../assets/fonts/NotoSerif_600SemiBold.ttf";
import NotoSerif_700Bold from "../../assets/fonts/NotoSerif_700Bold.ttf";

/**
 * Every face declared in the design tokens, registered under the same name.
 * Latin subsets (French, Wolof, Pulaar, Serer) generated by `pnpm fonts` from the
 * Google Fonts packages, checked in CI by `pnpm fonts:check` (PERF-04).
 */
const faces: Record<(typeof fontFace)[keyof typeof fontFace], number> = {
  NotoSans_400Regular,
  NotoSans_600SemiBold,
  NotoSans_700Bold,
  NotoSans_800ExtraBold,
  NotoSerif_600SemiBold,
  NotoSerif_700Bold,
};

/**
 * True once the fonts are usable. A loading failure also counts as ready:
 * the app then renders with the system font rather than staying blocked.
 */
export function useAppFonts(): boolean {
  const [loaded, error] = useFonts(faces);
  return loaded || error !== null;
}
