import type { fontFace } from "@bgs/ui";
import { useFonts } from "expo-font";
import BricolageGrotesque_600SemiBold from "../../assets/fonts/BricolageGrotesque_600SemiBold.ttf";
import BricolageGrotesque_700Bold from "../../assets/fonts/BricolageGrotesque_700Bold.ttf";
import BricolageGrotesque_800ExtraBold from "../../assets/fonts/BricolageGrotesque_800ExtraBold.ttf";
import Manrope_400Regular from "../../assets/fonts/Manrope_400Regular.ttf";
import Manrope_600SemiBold from "../../assets/fonts/Manrope_600SemiBold.ttf";
import Manrope_700Bold from "../../assets/fonts/Manrope_700Bold.ttf";
import Literata_600SemiBold from "../../assets/fonts/Literata_600SemiBold.ttf";
import Literata_700Bold from "../../assets/fonts/Literata_700Bold.ttf";

/**
 * Every face declared in the design tokens, registered under the same name.
 * Latin-only subsets (French, Wolof) generated by `pnpm fonts` from the Google Fonts
 * packages, checked in CI by `pnpm fonts:check` (PERF-04).
 */
const faces: Record<(typeof fontFace)[keyof typeof fontFace], number> = {
  BricolageGrotesque_600SemiBold,
  BricolageGrotesque_700Bold,
  BricolageGrotesque_800ExtraBold,
  Manrope_400Regular,
  Manrope_600SemiBold,
  Manrope_700Bold,
  Literata_600SemiBold,
  Literata_700Bold,
};

/**
 * True once the fonts are usable. A loading failure also counts as ready:
 * the app then renders with the system font rather than staying blocked.
 */
export function useAppFonts(): boolean {
  const [loaded, error] = useFonts(faces);
  return loaded || error !== null;
}
